#!/usr/bin/with-contenv bash

# Alpine
if [ -f /sbin/apk ]; then
    if ! apk info --installed wireguard-tools >/dev/null; then
        echo "**** Adding universal-wireguardvpn packages to install lists ****"
        echo "\
            grep \
            iproute2 \
            iptables \
            iptables-legacy \
            ip6tables \
            iputils \
            libcap-utils \
            net-tools \
            wireguard-tools" >> /mod-repo-packages-to-install.list
    else
        echo "**** Universal-wireguardvpn packages already installed, skipping ****"
    fi
fi

# Ubuntu
if [ -f /usr/bin/apt ]; then
    if ! apt list -i wireguard | grep installed >/dev/null; then
        echo "\
            grep \
            iproute2 \
            iptables \
            dnsutils \
            net-tools \
            wireguard" >> /mod-repo-packages-to-install.list
    else
        echo "**** Universal-wireguardvpn packages already installed, skipping ****"
    fi
fi
