#!/usr/bin/with-contenv bash

# Alpine
if [ -f /sbin/apk ]; then
    if ! apk info --installed wireguard-tools >/dev/null; then
        echo "**** Adding universal-wireguardvpn packages to install lists ****"
        echo "\
            grep \
            iproute2 \
            iptables \
            iptables-legacy \
            ip6tables \
            iputils \
            libcap-utils \
            net-tools \
            wireguard-tools" >> /mod-repo-packages-to-install.list
    else
        echo "**** Universal-wireguardvpn packages already installed, skipping ****"
    fi
else
    echo "**************************************************"
    echo "**                     WARNING                  **"
    echo "**                                              **"
    echo "** Mod not supported! Universal-wireguardvpn is **"
    echo "** only supported on Alpine based containers.   **"
    echo "**                                              **"
    echo "**************************************************"
    exit 1
fi
