#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2016,SC1091,SC2183


if [[ -n "$LAN_NETWORK" ]]; then

    echo "**** Configuring firewall for local network"

    lan_network_item="${LAN_NETWORK}"
    default_gateway_ip="$(ip route | grep default | cut -d " " -f 3)"
    default_gateway_adapter="$(ip route | grep default | cut -d " " -f 5)"

    ip route add "${lan_network_item}" via "${default_gateway_ip}" dev "${default_gateway_adapter}"

else

    echo "**** No local LAN specified"

fi