#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2016,SC1091,SC2183


echo "============ WG NETWORK CONF ==================="

lan_network_item="192.168.0.0/24"
default_gateway_ip="$(ip route | grep default | cut -d " " -f 3)"
default_gateway_adapter="$(ip route | grep default | cut -d " " -f 5)"

ip route add "${lan_network_item}" via "${default_gateway_ip}" dev "${default_gateway_adapter}"

echo "============== DONE =============="